export const IMG_URL = "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/"


export const restaurentList = [
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "709678",
        name: "Pizza Hut",
        uuid: "001771c3-afe8-4252-951b-a1b91e60665e",
        city: "4",
        area: "KAROL BAGH",
        totalRatingsString: "100+ ratings",
        cloudinaryImageId: "490629b70f89da8a5b93fc199ece335e",
        cuisines: ["Pizzas"],
        tags: [],
        costForTwo: 35000,
        costForTwoString: "₹350 FOR TWO",
        deliveryTime: 32,
        minDeliveryTime: 32,
        maxDeliveryTime: 32,
        slaString: "32 MINS",
        lastMileTravel: 2.200000047683716,
        slugs: {
          restaurant: "pizza-hut-ashram-marg-metro-karol-bagh",
          city: "delhi",
        },
        cityState: "4",
        address:
          "Pizza Hut at Lower Ground Floor, R.K. Ashram Marg Metro Station of Line-3 of DMRC Network, New Delhi, KAROL BAGH, Central, Delhi, 110055",
        locality: "Ashram Marg Metro",
        parentId: 721,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3100,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3100,
          message: "",
          title: "Delivery Charge",
          amount: "3100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "2.2 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "50% OFF",
          subHeader: "UPTO ₹100",
          discountTag: "",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "709678",
          deliveryTime: 32,
          minDeliveryTime: 32,
          maxDeliveryTime: 32,
          lastMileTravel: 2.200000047683716,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.5",
        totalRatings: 100,
        new: true,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "571586",
        name: "Prem Dhaba",
        uuid: "187bc490-a227-46e3-97a7-873f344048df",
        city: "4",
        area: "Karol Bagh",
        totalRatingsString: "1000+ ratings",
        cloudinaryImageId: "xk1thvk3rb4y99rliiea",
        cuisines: ["North Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 37,
        minDeliveryTime: 37,
        maxDeliveryTime: 37,
        slaString: "37 MINS",
        lastMileTravel: 4.800000190734863,
        slugs: {
          restaurant: "prem-dhaba-karol-bagh-karol-bagh",
          city: "delhi",
        },
        cityState: "4",
        address:
          "11139, New Rohtak Rd, Block 69D, Dori Walan,Karol Bagh, New Delhi,Delhi 110005",
        locality: "Dori Walan",
        parentId: 160936,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        ribbon: [
          {
            type: "PROMOTED",
          },
        ],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 4300,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 4300,
          message: "",
          title: "Delivery Charge",
          amount: "4300",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7426875~p=4~eid=00000189-590d-c03e-0cc4-04f100cf0403~srvts=1689416220734",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "4.8 kms",
        hasSurge: false,
        aggregatedDiscountInfoV3: {
          header: "₹100 OFF",
          subHeader: "ABOVE ₹599",
          discountTag: "FLAT DEAL",
          headerTypeV2: 0,
        },
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "571586",
          deliveryTime: 37,
          minDeliveryTime: 37,
          maxDeliveryTime: 37,
          lastMileTravel: 4.800000190734863,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.2",
        totalRatings: 1000,
        new: false,
      },
      subtype: "basic",
    },
    {
      type: "restaurant",
      data: {
        type: "F",
        id: "455426",
        name: "Rajdhani Restaurant",
        uuid: "de987ed6-d7b9-42c5-952e-dcb9a6b5db33",
        city: "4",
        area: "Paharganj",
        totalRatingsString: "500+ ratings",
        cloudinaryImageId: "nc22xejkzikzn9fnuwaf",
        cuisines: ["Afghani", "Biryani", "Chinese", "Indian", "North Indian"],
        tags: [],
        costForTwo: 10000,
        costForTwoString: "₹100 FOR TWO",
        deliveryTime: 36,
        minDeliveryTime: 36,
        maxDeliveryTime: 36,
        slaString: "36 MINS",
        lastMileTravel: 1.7999999523162842,
        slugs: {
          restaurant: "rajdhani-restaurant-karol-bagh-karol-bagh",
          city: "delhi",
        },
        cityState: "4",
        address:
          "SHOP NO-3850 FLOOR GALI TELYAN MANDI , PAHARGANJ , DELHI , 110055",
        locality: "Gali Telyan Mandi",
        parentId: 165492,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "distance",
              fee: 3100,
              message: "",
            },
            {
              name: "time",
              fee: 0,
              message: "",
            },
            {
              name: "special",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 3100,
          message: "",
          title: "Delivery Charge",
          amount: "3100",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "1.7 kms",
        hasSurge: false,
        loyaltyDiscoverPresentationInfo: {
          logoCtx: {
            text: "BENEFITS",
            logo: "v1634558776/swiggy_one/OneLogo_3x.png",
          },
          freedelMessage: "FREE DELIVERY",
          exclusiveOfferMessage: "",
        },
        sla: {
          restaurantId: "455426",
          deliveryTime: 36,
          minDeliveryTime: 36,
          maxDeliveryTime: 36,
          lastMileTravel: 1.7999999523162842,
          lastMileDistance: 0,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          longDistance: "NOT_LONG_DISTANCE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "2.8",
        totalRatings: 500,
        new: false,
      },
      subtype: "basic",
    },
  ];
  